# Streamlit Secrets Configuration (Confidencial)
# Puedes cambiar la contraseña de admin y la clave de invitado aquí o en los secretos de Streamlit Community Cloud

[auth]
admin_user = "admin"
admin_pass = "barca2026"
guest_key = "viscabarca"
