"""
2026-2027 FC Barcelona Fixture Calendar and Match Seeder.
Covers LaLiga (38 matchdays), Champions League (8 league phase matches), Copa del Rey, and Supercopa.
"""

from data_pipeline.data_loader import seed_season_data

MATCHES_2026_2027 = [
    # ==================== LALIGA 2026/2027 ====================
    {
        "id": "2627_LALIGA_J01",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 1,
        "stage": "Jornada 1",
        "date": "2026-08-27",
        "time": "21:00",
        "home_team": "FC Barcelona",
        "away_team": "Athletic Club",
        "is_barca_home": True,
        "opponent": "Athletic Club",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED",
        "notes": "Jornada 1 en Spotify Camp Nou"
    },
    {
        "id": "2627_LALIGA_J02",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 2,
        "stage": "Jornada 2",
        "date": "2026-08-23",
        "time": "21:30",
        "home_team": "Elche CF",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Elche CF",
        "venue": "Martínez Valero",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J03",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 3,
        "stage": "Jornada 3",
        "date": "2026-08-31",
        "time": "21:30",
        "home_team": "FC Barcelona",
        "away_team": "Rayo Vallecano",
        "is_barca_home": True,
        "opponent": "Rayo Vallecano",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J04",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 4,
        "stage": "Jornada 4",
        "date": "2026-09-06",
        "time": "16:15",
        "home_team": "Valencia CF",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Valencia CF",
        "venue": "Mestalla",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J05",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 5,
        "stage": "Jornada 5",
        "date": "2026-09-13",
        "time": "18:30",
        "home_team": "Levante UD",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Levante UD",
        "venue": "Ciutat de València",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J06",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 6,
        "stage": "Jornada 6",
        "date": "2026-09-16",
        "time": "20:00",
        "home_team": "FC Barcelona",
        "away_team": "Racing de Santander",
        "is_barca_home": True,
        "opponent": "Racing de Santander",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J07",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 7,
        "stage": "Jornada 7",
        "date": "2026-09-20",
        "time": "21:00",
        "home_team": "Sevilla FC",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Sevilla FC",
        "venue": "Ramón Sánchez-Pizjuán",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J08",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 8,
        "stage": "Jornada 8",
        "date": "2026-10-11",
        "time": "18:30",
        "home_team": "FC Barcelona",
        "away_team": "Getafe CF",
        "is_barca_home": True,
        "opponent": "Getafe CF",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J09",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 9,
        "stage": "Jornada 9",
        "date": "2026-10-18",
        "time": "21:00",
        "home_team": "Real Betis",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Real Betis",
        "venue": "Benito Villamarín",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J10",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 10,
        "stage": "Jornada 10",
        "date": "2026-10-25",
        "time": "21:00",
        "home_team": "FC Barcelona",
        "away_team": "Real Madrid",
        "is_barca_home": True,
        "opponent": "Real Madrid",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED",
        "notes": "El Clásico en Spotify Camp Nou"
    },
    {
        "id": "2627_LALIGA_J11",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 11,
        "stage": "Jornada 11",
        "date": "2026-11-01",
        "time": "18:30",
        "home_team": "FC Barcelona",
        "away_team": "Deportivo Alavés",
        "is_barca_home": True,
        "opponent": "Deportivo Alavés",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J12",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 12,
        "stage": "Jornada 12",
        "date": "2026-11-08",
        "time": "21:00",
        "home_team": "Atlético de Madrid",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Atlético de Madrid",
        "venue": "Riyadh Air Metropolitano",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J13",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 13,
        "stage": "Jornada 13",
        "date": "2026-11-22",
        "time": "16:15",
        "home_team": "FC Barcelona",
        "away_team": "Villarreal CF",
        "is_barca_home": True,
        "opponent": "Villarreal CF",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J14",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 14,
        "stage": "Jornada 14",
        "date": "2026-11-29",
        "time": "18:30",
        "home_team": "RC Deportivo de La Coruña",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "RC Deportivo de La Coruña",
        "venue": "Riazor",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J15",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 15,
        "stage": "Jornada 15",
        "date": "2026-12-06",
        "time": "21:00",
        "home_team": "FC Barcelona",
        "away_team": "RC Celta de Vigo",
        "is_barca_home": True,
        "opponent": "RC Celta de Vigo",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J16",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 16,
        "stage": "Jornada 16",
        "date": "2026-12-13",
        "time": "18:30",
        "home_team": "Málaga CF",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Málaga CF",
        "venue": "La Rosaleda",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J17",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 17,
        "stage": "Jornada 17",
        "date": "2026-12-20",
        "time": "21:00",
        "home_team": "FC Barcelona",
        "away_team": "Real Sociedad",
        "is_barca_home": True,
        "opponent": "Real Sociedad",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J18",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 18,
        "stage": "Jornada 18",
        "date": "2027-01-03",
        "time": "21:00",
        "home_team": "RCD Espanyol",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "RCD Espanyol",
        "venue": "RCDE Stadium",
        "status": "SCHEDULED",
        "notes": "Derbi Barcelonés"
    },
    {
        "id": "2627_LALIGA_J19",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 19,
        "stage": "Jornada 19",
        "date": "2027-01-10",
        "time": "18:30",
        "home_team": "CA Osasuna",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "CA Osasuna",
        "venue": "El Sadar",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J20",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 20,
        "stage": "Jornada 20",
        "date": "2027-01-17",
        "time": "16:15",
        "home_team": "FC Barcelona",
        "away_team": "Elche CF",
        "is_barca_home": True,
        "opponent": "Elche CF",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J21",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 21,
        "stage": "Jornada 21",
        "date": "2027-01-24",
        "time": "18:30",
        "home_team": "Deportivo Alavés",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Deportivo Alavés",
        "venue": "Mendizorrotza",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J22",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 22,
        "stage": "Jornada 22",
        "date": "2027-01-31",
        "time": "21:00",
        "home_team": "FC Barcelona",
        "away_team": "Valencia CF",
        "is_barca_home": True,
        "opponent": "Valencia CF",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J23",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 23,
        "stage": "Jornada 23",
        "date": "2027-02-07",
        "time": "21:00",
        "home_team": "FC Barcelona",
        "away_team": "Atlético de Madrid",
        "is_barca_home": True,
        "opponent": "Atlético de Madrid",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J24",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 24,
        "stage": "Jornada 24",
        "date": "2027-02-14",
        "time": "18:30",
        "home_team": "Villarreal CF",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Villarreal CF",
        "venue": "Estadio de la Cerámica",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J25",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 25,
        "stage": "Jornada 25",
        "date": "2027-02-21",
        "time": "16:15",
        "home_team": "FC Barcelona",
        "away_team": "Levante UD",
        "is_barca_home": True,
        "opponent": "Levante UD",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J26",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 26,
        "stage": "Jornada 26",
        "date": "2027-02-28",
        "time": "21:00",
        "home_team": "Athletic Club",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Athletic Club",
        "venue": "San Mamés",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J27",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 27,
        "stage": "Jornada 27",
        "date": "2027-03-07",
        "time": "18:30",
        "home_team": "FC Barcelona",
        "away_team": "Real Betis",
        "is_barca_home": True,
        "opponent": "Real Betis",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J28",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 28,
        "stage": "Jornada 28",
        "date": "2027-03-14",
        "time": "16:15",
        "home_team": "FC Barcelona",
        "away_team": "RC Deportivo de La Coruña",
        "is_barca_home": True,
        "opponent": "RC Deportivo de La Coruña",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J29",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 29,
        "stage": "Jornada 29",
        "date": "2027-03-21",
        "time": "21:00",
        "home_team": "Rayo Vallecano",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Rayo Vallecano",
        "venue": "Vallecas",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J30",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 30,
        "stage": "Jornada 30",
        "date": "2027-04-04",
        "time": "18:30",
        "home_team": "FC Barcelona",
        "away_team": "Sevilla FC",
        "is_barca_home": True,
        "opponent": "Sevilla FC",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J31",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 31,
        "stage": "Jornada 31",
        "date": "2027-04-11",
        "time": "16:15",
        "home_team": "Racing de Santander",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Racing de Santander",
        "venue": "El Sardinero",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J32",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 32,
        "stage": "Jornada 32",
        "date": "2027-04-18",
        "time": "21:00",
        "home_team": "FC Barcelona",
        "away_team": "RCD Espanyol",
        "is_barca_home": True,
        "opponent": "RCD Espanyol",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED",
        "notes": "Derbi Barcelonés"
    },
    {
        "id": "2627_LALIGA_J33",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 33,
        "stage": "Jornada 33",
        "date": "2027-04-21",
        "time": "21:30",
        "home_team": "RC Celta de Vigo",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "RC Celta de Vigo",
        "venue": "Balaídos",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J34",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 34,
        "stage": "Jornada 34",
        "date": "2027-05-02",
        "time": "18:30",
        "home_team": "FC Barcelona",
        "away_team": "CA Osasuna",
        "is_barca_home": True,
        "opponent": "CA Osasuna",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J35",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 35,
        "stage": "Jornada 35",
        "date": "2027-05-09",
        "time": "21:00",
        "home_team": "Real Madrid",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Real Madrid",
        "venue": "Santiago Bernabéu",
        "status": "SCHEDULED",
        "notes": "El Clásico en el Bernabéu"
    },
    {
        "id": "2627_LALIGA_J36",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 36,
        "stage": "Jornada 36",
        "date": "2027-05-16",
        "time": "18:30",
        "home_team": "Real Sociedad",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Real Sociedad",
        "venue": "Reale Arena",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J37",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 37,
        "stage": "Jornada 37",
        "date": "2027-05-23",
        "time": "19:00",
        "home_team": "FC Barcelona",
        "away_team": "Málaga CF",
        "is_barca_home": True,
        "opponent": "Málaga CF",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_LALIGA_J38",
        "season": "2026-27",
        "competition": "LaLiga",
        "matchday": 38,
        "stage": "Jornada 38",
        "date": "2027-05-30",
        "time": "19:00",
        "home_team": "Getafe CF",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Getafe CF",
        "venue": "Coliseum",
        "status": "SCHEDULED"
    },

    # ==================== CHAMPIONS LEAGUE 2026/2027 ====================
    {
        "id": "2627_UCL_J01",
        "season": "2026-27",
        "competition": "Champions League",
        "matchday": 1,
        "stage": "Fase Liga - J1",
        "date": "2026-09-09",
        "time": "21:00",
        "home_team": "FC Barcelona",
        "away_team": "Bayern Munich",
        "is_barca_home": True,
        "opponent": "Bayern Munich",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_UCL_J02",
        "season": "2026-27",
        "competition": "Champions League",
        "matchday": 2,
        "stage": "Fase Liga - J2",
        "date": "2026-10-14",
        "time": "21:00",
        "home_team": "AS Monaco",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "AS Monaco",
        "venue": "Stade Louis II",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_UCL_J03",
        "season": "2026-27",
        "competition": "Champions League",
        "matchday": 3,
        "stage": "Fase Liga - J3",
        "date": "2026-10-21",
        "time": "21:00",
        "home_team": "FC Barcelona",
        "away_team": "SL Benfica",
        "is_barca_home": True,
        "opponent": "SL Benfica",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_UCL_J04",
        "season": "2026-27",
        "competition": "Champions League",
        "matchday": 4,
        "stage": "Fase Liga - J4",
        "date": "2026-11-04",
        "time": "21:00",
        "home_team": "Borussia Dortmund",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Borussia Dortmund",
        "venue": "Signal Iduna Park",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_UCL_J05",
        "season": "2026-27",
        "competition": "Champions League",
        "matchday": 5,
        "stage": "Fase Liga - J5",
        "date": "2026-11-25",
        "time": "21:00",
        "home_team": "FC Barcelona",
        "away_team": "Atalanta BC",
        "is_barca_home": True,
        "opponent": "Atalanta BC",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_UCL_J06",
        "season": "2026-27",
        "competition": "Champions League",
        "matchday": 6,
        "stage": "Fase Liga - J6",
        "date": "2026-12-09",
        "time": "21:00",
        "home_team": "Stade Brestois",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Stade Brestois",
        "venue": "Stade Francis-Le Blé",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_UCL_J07",
        "season": "2026-27",
        "competition": "Champions League",
        "matchday": 7,
        "stage": "Fase Liga - J7",
        "date": "2027-01-20",
        "time": "21:00",
        "home_team": "FC Barcelona",
        "away_team": "BSC Young Boys",
        "is_barca_home": True,
        "opponent": "BSC Young Boys",
        "venue": "Spotify Camp Nou",
        "status": "SCHEDULED"
    },
    {
        "id": "2627_UCL_J08",
        "season": "2026-27",
        "competition": "Champions League",
        "matchday": 8,
        "stage": "Fase Liga - J8",
        "date": "2027-01-27",
        "time": "21:00",
        "home_team": "Crvena Zvezda",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Crvena Zvezda",
        "venue": "Rajko Mitić Stadium",
        "status": "SCHEDULED"
    },

    # ==================== SUPERCOPA 2027 ====================
    {
        "id": "2627_SUPERCOPA_SF1",
        "season": "2026-27",
        "competition": "Supercopa",
        "matchday": None,
        "stage": "Semifinal",
        "date": "2027-02-03",
        "time": "20:00",
        "home_team": "FC Barcelona",
        "away_team": "Atlético de Madrid",
        "is_barca_home": True,
        "opponent": "Atlético de Madrid",
        "venue": "Atatürk Olympic Stadium (Estambul)",
        "status": "SCHEDULED"
    },

    # ==================== COPA DEL REY 2026/2027 ====================
    {
        "id": "2627_CDR_16AVOS",
        "season": "2026-27",
        "competition": "Copa del Rey",
        "matchday": None,
        "stage": "Dieciseisavos",
        "date": "2026-12-16",
        "time": "21:00",
        "home_team": "Rival a Determinar",
        "away_team": "FC Barcelona",
        "is_barca_home": False,
        "opponent": "Rival a Determinar",
        "venue": "Campo Rival",
        "status": "SCHEDULED"
    }
]

def load_2026_2027(db_path="barca_analytics.db"):
    return seed_season_data(MATCHES_2026_2027, db_path)

if __name__ == "__main__":
    load_2026_2027()
